// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _Net_Proj_3.Migrations
{
    [DbContext(typeof(ApplicationDBConext))]
    [Migration("20250408174003_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Models.FastTagVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Balance")
                        .HasColumnType("INT")
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("FastTagSerial")
                        .HasColumnType("INT")
                        .HasColumnName("tag_serial");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("reg_num");

                    b.HasKey("Id");

                    b.ToTable("vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1000,
                            CreatedAt = new DateTime(2025, 4, 8, 23, 10, 3, 438, DateTimeKind.Local).AddTicks(7496),
                            FastTagSerial = 1234567890,
                            RegNumber = "KA-01-AB-1234"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
